### ISSUE TITLE
Error when selecting city in profile creation

### ISSUE THREAD

**Issue by alexresiga** [benawad/vsinder#1]
ios 14.2
copied stacktrace: https://d1wp6m56sqw74a.cloudfront.net/%40benawad%2Fvsinder%2F1.2.10%2Fcdba6172539608c912cf0a847b76e46f-39.0.0-ios.js:1781:10476

message: `null is not an object (evaluating 'O.length')`

**Comment by benawad** [comment]
should be fixed in latest version, you might need to totally close app and reopen to get it
