### ISSUE TITLE
app handle small screens

### ISSUE THREAD

**Issue by benawad** [benawad/vsinder#100]
![Screenshot_20201210-211457](https://user-images.githubusercontent.com/7872329/102017446-93a74380-3d2c-11eb-8c62-93a01f806865.png)

**Comment by unDeadHerbs** [comment]
![Screenshot_20201223-072952.png](https://user-images.githubusercontent.com/235057/103000430-acfc7c80-44f0-11eb-8d11-203b338dab50.png)

This seems to work just fine at the moment.  The only issue I can see is that, on the user profile screen, you can't read the profile image changing instructions.
