### ISSUE TITLE
[Bug] [Feature Request] Non-binary discrimination / More versatile gender filter

### ISSUE THREAD

**Issue by unDeadHerbs** [benawad/vsinder#103]
Currently non-binary people are systematically filtered out of the "I'm looking for: love" pool.  This is since, in order to see non-binary people, one has to select "Show me code from: everyone", where many are actively interested in not being offered their own gender.

Changing the "Show me code from:" to three check boxes instead of a radial selection will remove this systematic bias (even if not the human one).

**Comment by benawad** [comment]
So do you see the 3 checkboxes being `males`, `females`, `everyone` still or `males`, `females`, `non-binary` or something else?

**Comment by unDeadHerbs** [comment]
I'd go for `male`, `female`, and `non-binary` and default to all three checked.
