### ISSUE TITLE
I am getting likes on my profile but no matches🙄

### ISSUE THREAD

**Issue by rohith1125** [benawad/vsinder#104]
What does this mean? How are likes different from matches?

**Comment by kimlimjustin** [comment]
It's maybe because there are users who like you but you say "nope" to them, hence, there's no match.

**Comment by rohith1125** [comment]
No bro, I right swiped every profile...

**Comment by rohith1125** [comment]
I suspect there is a bug which doesn't let you see all the matches...

**Comment by kimlimjustin** [comment]
Ohh.. Maybe you can just wait for a moment or just continue right swipe because in my case I got a lot of matches.

**Comment by benawad** [comment]
@rohith1125 it looks like you have 3 matches?

**Comment by rohith1125** [comment]
Yes, I have 3 matches but 13 likes

**Comment by rohith1125** [comment]
How does it work? I right swiped every profile, so number of likes must be same as number of matches right?

**Comment by benawad** [comment]
did you run out of profiles?

**Comment by benawad** [comment]
looks like I had it where people who chose friendship could see everyone, so you got likes from people you couldn't see

good catch!

**Comment by rohith1125** [comment]
Yes, I ran out of profiles

**Comment by rohith1125** [comment]
> looks like I had it where people who chose friendship could see everyone, so you got likes from people you couldn't see
> 
> good catch!

Oh I get it now👍🏻, btw great idea
