### ISSUE TITLE
[Android] Login timeout too short

### ISSUE THREAD

**Issue by unDeadHerbs** [benawad/vsinder#111]
Nearly every time I open the app, I am greeted with a "refreshing" icon.  After a few seconds of this I am returned to the "new user" page with a banner about a network error.

This is probably because I've really high latency internet (Over a minute at times) and might only be an issue for Xfinity subscribers and those in the 3rd world.

**Comment by benawad** [comment]
what would you suggest setting it to?

**Comment by unDeadHerbs** [comment]
Since the app doesn't really have any functionality or purpose without network connectivity, I'd set it to the maximum it can be.  Loading the "new user" screen as well is probably good, but leave a banner saying that it's still trying.

**Comment by benawad** [comment]
Does this continue to happen? It looks like `fetch` in React Native doesn't have a timeout option

**Comment by unDeadHerbs** [comment]
Sometimes; but, pressing the "login with GitHub to get started" button isn't too much work.
