### ISSUE TITLE
don't get callback when I click the button "next" after editing the personal infomation.

### ISSUE THREAD

**Issue by zs963048949** [benawad/vsinder#114]

**Comment by benawad** [comment]
what do you mean by callback?

**Comment by zs963048949** [comment]
Can't enter into next step.



---Original---

**Comment by benawad** [comment]
on extension, iOS, or android? Is it possible there is an error popping up? Could you take a video?

**Comment by zs963048949** [comment]
It's in extension.It had been resulted. However,there was a little delay on the extension after I clicked some button.
