### ISSUE TITLE
Unable to edit bio

### ISSUE THREAD

**Issue by kirtan0000** [benawad/vsinder#115]
I cannot edit my bio on an iPad. There is no save button

**Comment by benawad** [comment]
Can you screenshot what it looks like? Did you scroll down?

**Comment by kirtan0000** [comment]
![IMG_1021](https://user-images.githubusercontent.com/67987854/102172024-d4967980-3e4c-11eb-98ac-b0892566cb06.jpeg)
there is no save button when i scroll down

**Comment by benawad** [comment]
oh apple requires me to only show button if you put 18 or older for your birthday
