### ISSUE TITLE
[Bug] Something is wrong with match gender filter

### ISSUE THREAD

**Issue by unDeadHerbs** [benawad/vsinder#117]
I noticed that I was being offered individuals who weren't aligned with my "Show me code from:" settings.  So, I unchecked all of the boxes.  After doing so, I was still offered code segments, rather than the blank queue I expected.

**Comment by benawad** [comment]
I'll change it so if you uncheck all no one shows up. Can you screenshot a profile you don't think should show up and the settings you used and I can double check it.

**Comment by unDeadHerbs** [comment]
![Screenshot_20201215-152951.png](https://user-images.githubusercontent.com/235057/102275011-656f6280-3eea-11eb-9042-e05b326a3c68.png)
![Screenshot_20201215-152943.png](https://user-images.githubusercontent.com/235057/102275025-699b8000-3eea-11eb-81ea-13573519061c.png)

**Comment by unDeadHerbs** [comment]
![Screenshot_20201215-155517.png](https://user-images.githubusercontent.com/235057/102277485-fc89e980-3eed-11eb-9f0d-b8a30caf76f9.png)
![Screenshot_20201215-155534.png](https://user-images.githubusercontent.com/235057/102277491-ff84da00-3eed-11eb-9f96-2b8fb77c8b77.png)

**Comment by benawad** [comment]
Looks like those users were just lying about their gender

**Comment by unDeadHerbs** [comment]
Well, there's quite a lot of them.  Some better way of discovering and reporting them well be needed.  I'll think on this.
