### ISSUE TITLE
ArrowUp and Spacebar/ArrowDown not working 

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [benawad/vsinder#118]
**Issue:**  On using ArrowUp for expanding bio or Spacebar/ArrowDown for swiping next photo, they do not work. Swiping is working only with h and l.

**Comment by unDeadHerbs** [comment]
Closed due to lack of second.

**Comment by codingride** [comment]
"ArrowUp: Expand bio" doesn't work

**Comment by codingride** [comment]
I just noticed that it does work when the profile description is more than two lines 
However, this "Spacebar or ArrowDown: Next photo" is also activated at the same time when I click arrowUp
