### ISSUE TITLE
Getting internal server error while trying to upload code snippet

### ISSUE THREAD

**Issue by Rudrava** [benawad/vsinder#12]
![image](https://user-images.githubusercontent.com/58327905/101657893-6d528100-3a6a-11eb-8aeb-791b19a2bcfd.png)
this is the ss of the error just for verification

**Comment by HariAcidReign** [comment]
Yep. I'm getting this bug as well. 
In addition to that, 

`Expected a value of type `Array<string & Pattern<^[\.a-z0-9\-]+$> & Length<0,30>> & Length<0,7>` for `codeImgIds` but received `[]`.`

**Comment by jsockchain** [comment]
Same here. Both errors.

**Comment by jsockchain** [comment]
Shouldn't be closed yet. The error persists and even new error.
```
The serverless lambda failed. This happens 50% of the time, try uploading your code again.
```
But this happens 100% of 10 times already.

**Comment by benawad** [comment]
darn, I thought I fixed it

**Comment by benawad** [comment]
@jsockchain are you still getting it?

**Comment by jsockchain** [comment]
Awesome. It is working now. 👍🏻
