### ISSUE TITLE
battery usage android

### ISSUE THREAD

**Issue by benawad** [benawad/vsinder#123]
![image](https://user-images.githubusercontent.com/7872329/102245414-24b02300-3ec3-11eb-83b7-754104b20470.png)

**Comment by bornmay** [comment]
Hii, Ben How it would be to even reduce the size of the images?

The application has fewer things, a bunch of API calls and a lot of swiping images, maybe that fixes the issue partially.

**Comment by unDeadHerbs** [comment]
I presume the only background task the app is doing is checking for new messages from the server.  I always have my android phone set to "battery saver". The app uses almost no battery with that enabled, if that helps.

**Comment by bornmay** [comment]
Yup, I have done this before once!


Use onBlur method with Stack Navigator.

When every user get away from the message screen, the sync will turn off!

const [sync, setSync]=useState(true)

<Stack.Navigator onBlur={setSync(false)}>

{sync ? Look for messages : " do noting"}


I guess this would work

**Comment by unDeadHerbs** [comment]
If I understand you correctly that would disable message notifications when the users are outside the app.  I expect just polling less frequently would be preferable.  I know android has hooks where it can decide when to poll for new messages with battery in mind.

**Comment by bornmay** [comment]
Sorry, but this is what I have done so far and know.

Will suerly look for android hook, you mentioned.

**Comment by unDeadHerbs** [comment]
@benawad Are you still experiencing this?

**Comment by unDeadHerbs** [comment]
Wrong buton.

**Comment by benawad** [comment]
This was someone else, but I assume it's still there

**Comment by Eloren1** [comment]
Nope, this app is more than two times more efficient in consumption than Telegram, Instagram and others. Even with longer background usage.
