### ISSUE TITLE
Flickering on snippet change

### ISSUE THREAD

**Issue by SanariSan** [benawad/vsinder#124]
`Device:` Meizu pro 6
`Android:` 6.0

`Problem:`

When it comes to person(1) that has several code snippets, 
tapping on them causes flicker so you can see next person's(2) code for half of a second, 
then it actually swaps the snippet of person(1) from like first to second and shows to you.
Not sure if it's intended to be like that.

`Suggested solution:`

When person has snippets - add additional bg layer with the color of chosen ide.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/76019273/102256943-1c84d180-3f1d-11eb-9bcc-556bc3a97a3a.gif)

**Comment by unDeadHerbs** [comment]
Fixed by #178.
