### ISSUE TITLE
Use codepush for OTA updates

### ISSUE THREAD

**Issue by avishayil** [benawad/vsinder#134]
Hi Ben,
On the last video, specifically here:
https://youtu.be/thqX845NEgg?t=732
You're complaining about every time you need to send an update to the app you have to go and wait for Apple to review it.
Just letting you know it's really easy to use `react-native-code-push` to send OTA updates, as long you're not compiling new binaries to your app (UI updates, functionality updates, etc).
https://github.com/microsoft/react-native-code-push
Happy to help, maybe using another Microsoft platform will get you an acquisition offer.

**Comment by benawad** [comment]
That's for the initial review before they let you into the store, I'm using something similar to code push now.
