### ISSUE TITLE
How do you delete your profile?

### ISSUE THREAD

**Issue by erf** [benawad/vsinder#14]
Could not find a way to delete the profile

**Comment by loxator** [comment]
I couldn't find this either, I have removed it from my **OAuth Authorized Applications** instead

**Comment by kiprasmel** [comment]
did you not enjoy the experience?:D

**Comment by YerinAlexey** [comment]
This was added in https://github.com/benawad/vsinder/commit/d5148a48730d0eef78eeabe9ca2b31e9e6fdaffb

**Comment by erf** [comment]
It looks like auth data was invalidated and userData set to null, but not sure if data is still persisted on disk or not..?
