### ISSUE TITLE
[Bug] Wrong status icons theme on Android

### ISSUE THREAD

**Issue by Pawelek99** [benawad/vsinder#143]
No matter what is my global Android Theme set to, when I change the theme inside the app to a different than "Solarized (dark)" the status bar icons are dark which makes them basically invisible. 

![image](https://user-images.githubusercontent.com/8677237/102476462-67a4fe80-405b-11eb-85d0-ad9b84092169.png)![image](https://user-images.githubusercontent.com/8677237/102476606-958a4300-405b-11eb-8f2d-09c4fb7fbcbd.png)

I have currently Android 10 on my phone and this is a custom build named PixelExperience.

**Comment by benawad** [comment]
update coming out soon that'll fix this
