### ISSUE TITLE
add github contributions to user profiles

### ISSUE THREAD

**Issue by charliexkilner** [benawad/vsinder#148]
Adding github contributions to profiles to see how loyal your potential match truly is!

Adding last year or 3 months of contributions as a slide to the profile could be a good idea and can be done as github profile is already logged in

**Comment by unDeadHerbs** [comment]
I don't think this is an impartial filter.  It groups together people who don't do anything and people whose company forbids open tools.  I agree it would be nice to know; but, #20 would provide access to this information without allowing for the app to discriminate.

**Comment by unDeadHerbs** [comment]
I'm closing this in favor of #20, might be reopened if that's accepted.
