### ISSUE TITLE
[Feature Request] Longer code segments

### ISSUE THREAD

**Issue by Adamkaram** [benawad/vsinder#151]

**Comment by unDeadHerbs** [comment]
Could you please change the title to
> [Feature Request] Longer code segments

I agree that 600 might be too short.  The picture size is limited enough already.

**Comment by Adamkaram** [comment]
> Could you please change the title to
> 
> > [Feature Request] Longer code segments
> 
> I agree that 600 might be too short. The picture size is limited enough already.

can we make it  1200 word it's size of 2 sinippet  and merge them toghter with some package like 
https://github.com/lukechilds/merge-images

with check of words like 
take the first 600  words and give theem snippet   same with the rest of code (600 words )
and grab those 2 images merge them together

**Comment by unDeadHerbs** [comment]
This depends on the resolution of #136.
