### ISSUE TITLE
Swipe only on females?

### ISSUE THREAD

**Issue by thousandsofraccoons** [benawad/vsinder#152]
Without this it's not fun

**Comment by unDeadHerbs** [comment]
Could you clarify your question?  There already exists a gender filter if you select "I'm looking for: love".

**Comment by thousandsofraccoons** [comment]
Oh, that's not very intuitive. Why I can't look up specifically for females to befriend?

**Comment by unDeadHerbs** [comment]
Because if you just want to be friends the gender "shouldn't" matter.
