### ISSUE TITLE
[Feature request] Card info on top! 

### ISSUE THREAD

**Issue by jasonesse** [benawad/vsinder#161]
UX feature to ease eye movement when reading code and checking user info-please position user info on top instead of the bottom so eyes can see code, avatar and text in one swoop.

**Comment by unDeadHerbs** [comment]
This would increase the visual importance of the bio and avatar to be greater than the code.  (At least it would with how I envision this change.)  I feel that this would be against the core aesthetic of the app.  However, I do agree that the distance between the code and the info is rather large.  Hopefully #149 will fix that by encouraging people to not only have one line of code.

**Comment by RazerMoon** [comment]
I agree with @unDeadHerbs, the app is meant to look like Tinder after all.

**Comment by unDeadHerbs** [comment]
I move to close, any dissenting arguments?

**Comment by jasonesse** [comment]
Does tinder allow the choice of color themes like vsinder? I like that users have the choice. 
Please consider offering the choice (bottom, top) for those who are interested in that option.
I don't use tinder so I wasn't aware of it's design choices.

**Comment by RazerMoon** [comment]
That's a fair point. However, imo, I don't think enough people care about it enough for it to become a big concern. I'm sure a pull request with this feature would be well received though.

**Comment by jasonesse** [comment]
I'd like to create a pull request for this, are any developers on a Windows machine? Trying to get it working locally with reddis.

**Comment by benawad** [comment]
@jasonesse have you tried https://redislabs.com/blog/redis-on-windows-10/

**Comment by jasonesse** [comment]
@benawad is there currently padding added to the bottom of each code image to support user info? Looks like the info is over the image and not under it. Placing it on top covers the code in the image.

**Comment by benawad** [comment]
@jasonesse nope, but the character limit usually prevents overflow
