### ISSUE TITLE
Formatting of number broken

### ISSUE THREAD

**Issue by OskarZyg** [benawad/vsinder#166]
![image](https://user-images.githubusercontent.com/56176746/102798844-926bbb80-43a9-11eb-8130-1935abcf0277.jpeg)

**Comment by kishanhitk** [comment]
![Screenshot_20210111-141427](https://user-images.githubusercontent.com/41117038/104160633-73e06980-5417-11eb-8be1-3a0cd4703d07.png)

Same issue here.

**Comment by kishanhitk** [comment]
![Screenshot_20210111-141555](https://user-images.githubusercontent.com/41117038/104160702-907ca180-5417-11eb-8fb9-d1100ad46c20.png)

Same issue here.
