### ISSUE TITLE
Compatibility with newest VS (v1.50.1)

### ISSUE THREAD

**Issue by orbli** [benawad/vsinder#169]
![image](https://user-images.githubusercontent.com/6440599/102850173-bedc1200-4453-11eb-92bb-1838b53dd3a2.png)

**Comment by benawad** [comment]
it's actually the other way around, it supports 1.51+ so you are on an older version I think

**Comment by orbli** [comment]
urk i thought after autoupdate this morning im on newest, sorry for confusion
