### ISSUE TITLE
plz explain this man 

### ISSUE THREAD

**Issue by XXX6000USER** [benawad/vsinder#174]
i have 101 likes yet only manage to match with 4 only idk get how it works

**Comment by unDeadHerbs** [comment]
You have to like someone who also likes you.  If you don't like the people who like you then you won't be matched with them.

**Comment by XXX6000USER** [comment]
> You have to like someone who also likes you. If you don't like the people who like you then you won't be matched with them.

lol yeah i discovered that  man i feel so dumb for the question sorry
