### ISSUE TITLE
[Feature request] block user based on his actions

### ISSUE THREAD

**Issue by Adamkaram** [benawad/vsinder#175]
the idea is there is some useres keep like every thing without see what is going on can we detect how much likes hit per 3 seconde or 6s what ever and we put his snippet in front of him or copy of it with the same id for him  if he liked it will got blocked

**Comment by unDeadHerbs** [comment]
> there are some users who keep everything without seeing what is going on

I'm not sure what you mean here or why it is bad.

**Comment by Adamkaram** [comment]
> > there are some users who keep everything without seeing what is going on
> 
> I'm not sure what you mean here or why it is bad.

keep liking  every snippet appear to them

**Comment by unDeadHerbs** [comment]
There is already a maximum of 500 likes per 9 hours (If I recall correctly) and users people have to like them back.  I don't see how this is a problem.  Sure, it's not exactly how the app is meant to be used; but, it doesn't hurt the other users.
