### ISSUE TITLE
[Dev] Cannot start app

### ISSUE THREAD

**Issue by RazerMoon** [benawad/vsinder#176]
I may be an idiot, but I followed the steps in the README and I get this error when I use `yarn start` and try to scan the QR code:
`Error: ENOENT: no such file or directory, open 'C:\Users\(name here)\Documents\GitHub\vsinder\packages\app\google-services.json'`

![image](https://user-images.githubusercontent.com/33849459/102997958-1cd52c00-451e-11eb-8f70-cb62c4080520.png)

![image](https://user-images.githubusercontent.com/33849459/102998056-4a21da00-451e-11eb-8f10-c07bef375eba.png)

![tempFileForShare_20201223-125824](https://user-images.githubusercontent.com/33849459/102998264-bf8daa80-451e-11eb-81df-c170108e8b46.jpg)

**Comment by benawad** [comment]
Remove the `"googleServicesFile": "./google-services.json",` line from `app.json` for now

**Comment by RazerMoon** [comment]
That worked, thanks. Ran into a couple of issues afterwards that I had to fix real quick.

For anybody else that could run the extension fine but is struggling with the app:
**DISCLAIMER, ONLY DO THIS IF YOU'RE TRYING TO RUN THE APP ON A PHONE, NOT EMULATOR**

- Change the __DEV__ apiBaseUrl to the IP of the machine you're running the API on, **NOT LOCALHOST** (the line below)
https://github.com/benawad/vsinder/blob/b3f9958c5b30e2a3029e24c054ce1def2b80b176/packages/app/src/constants.ts#L591-L593
![image](https://user-images.githubusercontent.com/33849459/103017219-3173ed00-453b-11eb-822f-b1a7e5f514b0.png)

- Change the GitHub auth callback url to the IP of the machine you're running the API on, **NOT LOCALHOST**
![image](https://user-images.githubusercontent.com/33849459/103017179-21f4a400-453b-11eb-9306-57279fa0b01c.png)
