### ISSUE TITLE
I haven't matched with the one I am looking for </3

### ISSUE THREAD

**Issue by bfu4** [benawad/vsinder#183]
So I have this person following me on Twitter. We are mutuals, however I have not spoken with them. He is very intent on starting conversations via VSinder, so I thought I should get on this app to try to talk to him. However, I've gone through majority of the people on this app, and I've not found him. 😢 💔 

Is there a possible reason for why I have not matched with [@Copystrike](https://github.com/Copystrike) on VSinder or was it just not meant to be. He tweeted at me when he found me, however I've not found him yet. 😭 Could it have been possible that I accidentally swiped left on him?

**Comment by unDeadHerbs** [comment]
The only "fix" I can think of for this would be a search feature.  This might be a good idea, and would make sense if #20 happens.

**Comment by benawad** [comment]
@bfu4 I just checked, you did swipe left on him, would you like me to undo that?

**Comment by bfu4** [comment]
@benawad yes please!! thank you 😊

**Comment by Copystrike** [comment]
😢

**Comment by benawad** [comment]
@bfu4 ok if you fully close/reopen he should show back up
