### ISSUE TITLE
messages disappear within 3 seconds

### ISSUE THREAD

**Issue by AlexaKhomenko** [benawad/vsinder#185]
hi, I do not see my messages, it first appear - then disappear abruptly.
thanks

**Comment by unDeadHerbs** [comment]
Please provide more information.  What platform is this on?

**Comment by AlexaKhomenko** [comment]
> Please provide more information. What platform is this on?

benawad/vsinder

**Comment by unDeadHerbs** [comment]
iPhone, Android, VScode?

**Comment by AlexaKhomenko** [comment]
> iPhone, Android, VScode?

iPhone

**Comment by AlexaKhomenko** [comment]
> > iPhone, Android, VScode?
> 
> iPhone

when I delete old matches- new messages from users appear

**Comment by unDeadHerbs** [comment]
This might be related to #173, how many matches do you have?

**Comment by AlexaKhomenko** [comment]
> This might be related to #173, how many matches do you have?

Yes, probably. I have 149-150 matches

**Comment by unDeadHerbs** [comment]
Closing in preference of existing report.  Thank you for your input.
