### ISSUE TITLE
Filter error

### ISSUE THREAD

**Issue by kirill21788** [benawad/vsinder#186]
I choose c#, but app take me js, c, c++, python and other all time

**Comment by unDeadHerbs** [comment]
That's a flair not a filter. It's just too show your allegiance.

**Comment by kirill21788** [comment]
> That's a flair not a filter. It's just too show your allegiance.

I guessed)) but in the article where I learned about this application, it was said about a specific language filter. and if it's not him, then where is he?)

**Comment by kirill21788** [comment]
> > That's a flair not a filter. It's just too show your allegiance.
> 
> I guessed)) but in the article where I learned about this application, it was said about a specific language filter. and if it's not him, then where is he?)

https://tjournal.ru/internet/247185-vsinder-tinder-dlya-programmistov-gde-nuzhno-svaypat-kod-a-ne-fotografii

First after title

**Comment by unDeadHerbs** [comment]
It also says you can register with Apple ID, which I believe is false.
