### ISSUE TITLE
Add pronouns to bio and "Trans" or "Other" as a gender option

### ISSUE THREAD

**Issue by Amanse** [benawad/vsinder#19]
Pronouns in bio will help normalise this for trans folks out there and would prevent the use of wrong pronouns, and they will be able to express their true gender with the gender option

**Comment by JCDetwiler** [comment]
Absolutely this. I think the matching options and algorithm will likely need to be updated as well.

**Comment by Amanse** [comment]
Thanks!!! once the algorithm is thought out i hope it gets merged soon!!

**Comment by phaux** [comment]
There are countries where outing yourself as transgender could get you fired, so specifying whether you're cis/trans should be at least optional (or just leave it as something to put in bio)

**Comment by Amanse** [comment]
Don't worry, it is optional, you decide what gender to enter, the app doesn't force you, neither do we, but for people who are out, this option is necessary
