### ISSUE TITLE
[web] Wrong page title for leaderbord, but only in production

### ISSUE THREAD

**Issue by LinqLover** [benawad/vsinder#194]
![img](https://user-images.githubusercontent.com/38782922/103466959-3cecc280-4d4a-11eb-8a40-5c203b55fb34.png?s=40)

but

![image](https://user-images.githubusercontent.com/38782922/103466967-54c44680-4d4a-11eb-9a82-d39a8a78e88a.png)

So probably something is wrong with the CD cycle ...?

**Comment by benawad** [comment]
I just deployed the changes and it's good now
