### ISSUE TITLE
[Feature Request] Select area to search in

### ISSUE THREAD

**Issue by hallohallo133** [benawad/vsinder#205]
It would be great, if it would be selectable in which area you want to look for new friends. For example if you want to find people who speak your native language. 
(Or am I just to stupid to find this option?)

**Comment by unDeadHerbs** [comment]
The filters live under "edit profile".  Currently the only filters are "Gender" and "Age Range", both of which only show up if you are "looking for: love".

Location based searching is temporally missing, see #135.
There is an open request for filtering on spoken languages, #106.
