### ISSUE TITLE
Hey, when will we able to upload pictures on there ?

### ISSUE THREAD

**Issue by pierreminiggio** [benawad/vsinder#210]
I'm talking about travel experiences with someone on this app.
Would be great if we could upload images in the chat so I could upload photos :D

**Comment by jsmon** [comment]
I'm not sure that's a good idea after what happened to VSCode Stories...

**Comment by pierreminiggio** [comment]
I don't know about VSCode Stories, so I don't have the context.

**Comment by jsmon** [comment]
Ok watch this video https://youtu.be/CHO316LKnZw

**Comment by pierreminiggio** [comment]
Oh ok, got it.
