### ISSUE TITLE
Business/Dev partners? 

### ISSUE THREAD

**Issue by rw3iss** [benawad/vsinder#212]
Man, where is your brain? Put all the work in for "friends" or "lovers"? First thought was what a great opportunity it might be to connect for potential business or development partnerships. Why not just add those two options for "looking for"? You'd probably increase your user base exponentially. I could care less about friends or lovers in the world of swiping random code on an app, personally. Nice looking app, though. Wish it had some business potential!

**Comment by unDeadHerbs** [comment]
I like the idea of this, it would increase the user base and thereby the utility of the app and it may by a successful idea; however, this would require letting users make multiple public faces, one for each "I'm looking for" selection.  Users probably don't want to use their dating profile for their resume, or vice versa.

**Comment by rw3iss** [comment]
Yeah that makes sense. However, you ARE losing the people who are only interested in one way anyway. People who are using the app for love AREN'T using it for business, so they don't care about the other face, and vice-versa. I doubt people would even want to use it for two purposes, or have two faces.
