### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by voltflake** [benawad/vsinder#256]
I understand that it may be costly to operate API service but at least confirm that project is closed or something.  

Also I'm sure someone could host API endpoint at this stage (not many people use it currently). I could do it on my Raspberry Pi. Maybe with outages because of Russian rockets but it's better than nothing, right? Anyway, feel free to contact me about this thing.  

Waiting for status updates about this project

**Comment by omginput** [comment]
Me too, whats going on?

**Comment by unDeadHerbs** [comment]
I presume @benawad has stopped paying for a server.  (Or has forgotten and an account expired.)

I'll host the API if he responds.

**Comment by SamuelChih** [comment]
Any updates on this?

**Comment by unDeadHerbs** [comment]
Not yet.  Anybody else know what to do to fix this?  I have PR Privileges and sys admin experience.

**Comment by Cheos137** [comment]
By now, the domain registration for `vsinder.com` seems to have run out.. and it looks like it'd be rather costly to reaquire..
if anything, one would have to use another domain (maybe `vsinder.net` or `vsinder.dev`  - they seem to be available and affordable) - that would require a vscode extension update though (changing the domain there, too)

everything else should just be figuring out which subdomains are used and properly setting them up to point to a server running the vsinder backend

**Comment by chagai95** [comment]
I can publish the app on the playstore if that's also open source, I can probably also host the api if someone wants to help me install that properly, let's get of the ground again! 

Ben Awad lost interest a long time ago and he actually sold this already so it's up to us 😎 

Here are my contract details: https://chagai.website

**Comment by voltflake** [comment]
vscode extension must be updated to point to right domain or IP if It needs to be changed. Who have access to extension published in vscode store?

**Comment by chagai95** [comment]
I think it's better to just release a new extension instead of waiting for a reply....

**Comment by Cheos137** [comment]
Though it'll be a bit inconvenient to re-release it, as the display name __must__ be unique (as must the id, obviously) in the vscode extension store.
Also, we would have to somehow spread word that there is a continuation you'd have to switch to.

**Comment by erikLundstedt** [comment]
> Though it'll be a bit inconvenient to re-release it, as the display name **must** be unique (as must the id, obviously) in the vscode extension store. Also, we would have to somehow spread word that there is a continuation you'd have to switch to.

New name idea:
Neo-vsinder

As with many things before 
Neo-vim
Nsxiv(the n here could also stand for new...)

**Comment by voltflake** [comment]
At this point this is basically re-implementing and re-releasing old vstinder because original owner disappeared. I don't think there is much sense to do it because all prior users will be gone and there is no popular YouTubers or other people to get attention to this app. It's probably not worth it.

**Comment by voltflake** [comment]
Or we can gather a small team, make a discord server or something and re-release it anyway🤔

**Comment by Cheos137** [comment]
Well, regarding the vscode extension, it would be possible to publish it to the same extension id as long as the original author authorizes some of us to it... whether that could happen is another thing, though

edit: i don't know anything about how app store / play store work, so can't say whether something could be done there

**Comment by Thelm76** [comment]
> > Though it'll be a bit inconvenient to re-release it, as the display name **must** be unique (as must the id, obviously) in the vscode extension store. Also, we would have to somehow spread word that there is a continuation you'd have to switch to.
> 
> New name idea: Neo-vsinder
> 
> As with many things before Neo-vim Nsxiv(the n here could also stand for new...)

Or Vsinderium x)
Or Codinder

**Comment by omginput** [comment]
Any news?

**Comment by voltflake** [comment]
@omginput this app is dead. The only solution is to make alternative to it. From scratch or by forking and refactoring this repo's code as well as hosting backend by yourself.

**Comment by whyisthesheep** [comment]
Are there any advancements?

**Comment by iamkisly** [comment]
I left a comment under Ben's latest video and it looks like it's been deleted now. I don't see it in the control panel. It is very strange.

**Comment by ragnarbull** [comment]
See the issue I just raised #262 . The URLs for GitHub and the ToS redirect to some malicious website prompting for a "security scan". I've reported to Microsoft and requested a takedown.
