### ISSUE TITLE
"This site can't be reached" when trying to auth github

### ISSUE THREAD

**Issue by nullopt** [benawad/vsinder#26]
After successfully signing into GitHub to auth, i'm redirected to localhost:54321 which says "This site can't be reached"
![chrome_2020-12-09_22-37-37](https://user-images.githubusercontent.com/18064964/101697219-54989a00-3a6f-11eb-9f53-33f5452bcc0a.png)

**Comment by benawad** [comment]
if you press login again, does it work?

**Comment by nullopt** [comment]
It just redirects me back to this page. I'm unable to authorize into the extension

**Comment by benawad** [comment]
the extension starts a server on port 54321 on localhost https://github.com/benawad/vsinder/blob/master/src/authenticate.ts#L11 and it looks like it can't connect to that for some reason.

1. Do you have something that would stop you from connecting to localhost?
2. If not, maybe the server is failing to startup. Try toggling devtools from the command palette and see if there is an error in there 
![image](https://user-images.githubusercontent.com/7872329/101710763-c2d16280-3a57-11eb-9b1a-9080fa1e8116.png)

**Comment by mohamed-azhar** [comment]
Same happened to me. Did a workaround by copying the link to a new incognito tab and by removing the s from https.

**Comment by LinqLover** [comment]
Doesn't work for me either, not even in incognito mode. I was installing VSinder in a remote session (using the VS Code Remote extension). Probably this extension needs better support for remote sessions?

**Comment by benawad** [comment]
I'm not sure if it's possible to auth with remote sessions if the localhost is different then your local comp

**Comment by LinqLover** [comment]
Hm ... VS Code Remote extension is able of forwarding ports to your local system, so this might be only a question of effort? The good news is that, after authenticating VSinder from a non-remote editor window, you can use it in remote windows, as well.

**Comment by benawad** [comment]
does it automatically forward ports or do you need to specify them

**Comment by LinqLover** [comment]
The latter is the case.

**Comment by benawad** [comment]
could you try forwarding port 54321 and see if it works for you

**Comment by LinqLover** [comment]
Ah, the latest VS Code release has brought automatic port forwarding, and now the extension works in remote contexts as well. All fine :-)
