### ISSUE TITLE
Malicious redirect links - please review ASAP

### ISSUE THREAD

**Issue by ragnarbull** [benawad/vsinder#262]
The redirect on the ToS and when you try to click "allow" brings up a nasty looking webpage. The domain is getting redirected...probably best to take the ext down until you work out how that's happened. Lots of malicious VS Code extensions recently so I have reported to VS Code. 

<img width="1225" alt="image" src="https://github.com/benawad/vsinder/assets/83689282/0ddfdc56-53f3-4f51-9d4f-02496b89c30c">

**Comment by ragnarbull** [comment]
PS. I don't have McAfee so no way am I clicking scan!!!

**Comment by ragnarbull** [comment]
And when I check my Google account Privacy & Security settings:

<img width="360" alt="image" src="https://github.com/benawad/vsinder/assets/83689282/e1c85176-b61e-44ff-b9d5-c67110a068fd">

Not good at all!

**Comment by Cheos137** [comment]
it's probably just the domain being bought by someone else... now redirecting everything to a malicious site - so nothing ben or anyone here could change/prevent, thus a takedown from the vscode extension repo (or removing the links from there) is the only thing that seems reasonable

**Comment by ragnarbull** [comment]
yeah exactly - edited my comment above. I wrote that its probably a domain takeover in the other issue. thanks

**Comment by voltflake** [comment]
Bens software now acts like a malware, a catchy title for future video 😏
Let's just hope he unpublishes vscode extension as soon as possible...

**Comment by ragnarbull** [comment]
MSFT just took it down

![vs-code-takedown](https://github.com/benawad/vsinder/assets/83689282/8bb740a8-6369-46b2-8c95-ba582c1e2f81)
