### ISSUE TITLE
error on click "save code snippet"

### ISSUE THREAD

**Issue by samualtnorman** [benawad/vsinder#3]
no matter what I do, when I click "save code snippet", a notification appears in the bottom left:
```
{"message":"Internal Server Error"}
```
I'm taken to the page where my preview should be but all I have is a "+ add another" button.

I'm also given the options to "save" which leads to another error:
```
`Expected a value of type `Array<string & Pattern<^[\.a-z0-9\-]+$> & Length<0,30>> & Length<0,7>` for `codeImgIds` but received `[]`.
```

**Comment by vilhelmprytz** [comment]
Same for me, I think he is working on it: https://twitter.com/benawad/status/1336696657950478338
