### ISSUE TITLE
Pressing spacebar to display next photo is not working

### ISSUE THREAD

**Issue by lordvidex** [benawad/vsinder#32]
> Keyboard shortcuts:
 ArrowLeft: Nope
 ArrowRight: Like
 Spacebar: Next photo

These are the shortcuts as displayed in the VSCode application.
NB: I am running the app on a MacOS Big Sur 11.0.1

**Comment by benawad** [comment]
do you have focus in the window and do the arrow keys work for you?

**Comment by lordvidex** [comment]
Yes, focus is in windows, arrow keys work! it's just the spacebar
