### ISSUE TITLE
Age not calculated correctly

### ISSUE THREAD

**Issue by SH4D0WKING** [benawad/vsinder#34]
![image](https://user-images.githubusercontent.com/57136208/101779206-3b3a3100-3af5-11eb-9acb-20560b093abb.png)

Last time I checked I am 18, here it says im 17 however

**Comment by bmoe24x** [comment]
> ![image](https://user-images.githubusercontent.com/57136208/101779206-3b3a3100-3af5-11eb-9acb-20560b093abb.png)
> 
> Last time I checked I am 18, here it says im 17 however

Fixed by #27 there is a issue with months due to 1-based indexing instead of zero-based

**Comment by aalekhpatel07** [comment]
18 years is approximately `_c = 567648000000`ms. Maybe just replace the body with
```javascript
return new Date().getTime() - birthday.getTime() >= _c
```
for a clean implementation?
