### ISSUE TITLE
'Not Authenticated Error' keeps popping up 

### ISSUE THREAD

**Issue by schezfaz** [benawad/vsinder#39]
The not-authenticated error keeps showing up after a lot of button clicks!

A couple of swipes, switching screens from the profile view to the chat section, the back button --  some combination of these actions keeps triggering this error sigh.

(PS. Ben, thankyou so much ahaha this is great  i'm loving this quite a bit xD )

![image](https://user-images.githubusercontent.com/28871211/101803545-a6582780-3b36-11eb-9cc5-6dc41d7bfa2d.png)

**Comment by benawad** [comment]
if you close vscode and reopen it does it persist?

**Comment by schezfaz** [comment]
Ah, no not anymore. Seems to be a sporadic thing!
