### ISSUE TITLE
Received Messages and Sender keep getting temporarily mixed up

### ISSUE THREAD

**Issue by schezfaz** [benawad/vsinder#40]
So, I'm using this extension. Matched with a couple of people, pretty cool haaha. 

Howeverrrrrrrrrrrr, I'm talking to a couple of my matches simultaneously, and when i'm in the chat section of one of the matches, and another sends a message, the new message appears in the chat box of the chat that's currently open. 

Confused me a little, cause i was having 2 separate conversations about separate things with separate people xD

![vsinder](https://user-images.githubusercontent.com/28871211/101805676-094abe00-3b39-11eb-80e1-1c0fc21f80d6.gif)

**Comment by benawad** [comment]
should be fixed in latest version
