### ISSUE TITLE
Chat icon reads 1, even when no new messages/matches are present

### ISSUE THREAD

**Issue by schezfaz** [benawad/vsinder#42]
The chat icon indicates (1) as in 1 new message/match, even when all messages have been read and no new messages are present.

![vsinder1](https://user-images.githubusercontent.com/28871211/101807000-9d695500-3b3a-11eb-92eb-15938b2eeead.gif)

**Comment by benawad** [comment]
Published an update which I think should fix this, let me know if you still see anything weird

**Comment by schezfaz** [comment]
Ayy, good stuff Ben! Seems fine now! :'))
