### ISSUE TITLE
utf8mb4 chars dont work

### ISSUE THREAD

**Issue by jonnytest1** [benawad/vsinder#43]
database doesnt support emojis  (probably need to switch to utf8mb4 collation)

**Comment by unDeadHerbs** [comment]
Where and what does this cause as a problem?

**Comment by jonnytest1** [comment]
i cant post emojis in text fields

**Comment by unDeadHerbs** [comment]
Emoji work in the chat on Android.  Are you on iPhone or VScode?

**Comment by jonnytest1** [comment]
they dont work in code previews

**Comment by unDeadHerbs** [comment]
Duplicate of #16.
