### ISSUE TITLE
Age detection not always working

### ISSUE THREAD

**Issue by beniaminterza** [benawad/vsinder#45]
If I select november 2002 as my birthday, it says that i am 17

**Comment by bmoe24x** [comment]
> If I select november 2002 as my birthday, it says that i am 17

When did you experience this issue? This should have been resolved in #27 so might need to update

**Comment by benawad** [comment]
Published an update which I think should fix this, let me know if you still see anything weird

**Comment by bmoe24x** [comment]
Whoops made the same change and forgot PR it. Still an issue with the day part of the birthday will try to post a gif

**Comment by bmoe24x** [comment]
Day of birth still seems to decrement after save. When I was working on the change you eventually made I was trying to find what was going wrong here but I didnt see anything stick out, looks like you are handling day pretty similar to year and it isnt happening to year. Could this be somewhere on something serverless/backend? Maybe a mismatch of using a date string with `/` somewhere and `-` somewhere else? Not sure @benawad 

![vsinder_issue](https://user-images.githubusercontent.com/38509504/101859291-0ba91a00-3b31-11eb-9709-e9112b73d884.gif)

**Comment by benawad** [comment]
are you on the latest version, I'm not able to replicate

**Comment by bmoe24x** [comment]
i was on 1.10 i think at the time, still doing this now on 1.12

**Comment by unDeadHerbs** [comment]
Checking my birthdate, the bug was present on android but is now gone. Is it still present on VS code?

**Comment by unDeadHerbs** [comment]
Closing due to lack of interest and further reports.
