### ISSUE TITLE
have a way to see profile card when no messages have been sent

### ISSUE THREAD

**Issue by benawad** [benawad/vsinder#47]

**Comment by schezfaz** [comment]
Also, in addition to this, it would be great if the chat interface displayed the name of the person you are talking to! Maybe between the back and report buttons?

**Comment by viAtom** [comment]
Well, you can when you click on the profile picture. But I agree with the profile link on the chat interface

**Comment by viAtom** [comment]
Can't you already when you click on the profile picture (https://streamable.com/nujf41) ?

**Comment by schezfaz** [comment]
> Can't you already when you click on the profile picture (https://streamable.com/nujf41) ? 

@viAtom 

I think he means from within the chat interface!

**Comment by viAtom** [comment]
> > Can't you already when you click on the profile picture ([streamable.com/nujf41](https://streamable.com/nujf41)) ?
> 
> @viAtom
> 
> I think he means from within the chat interface!

In this case yeah your point should be the best way, showing the name and you can click on it :)

**Comment by unDeadHerbs** [comment]
This has been fixed on Android, is it still present on Vs-code or IOS?

**Comment by unDeadHerbs** [comment]
Closing due to probably being fixed on all platforms.
