### ISSUE TITLE
Page refreshing 

### ISSUE THREAD

**Issue by supperdoggy** [benawad/vsinder#54]
when you switch vs code windows it refreshes the page. I didn't swipe the card

![image](https://user-images.githubusercontent.com/49492887/101918473-136ccb00-3bd2-11eb-8937-f3b3cc4194c6.png)
![image](https://user-images.githubusercontent.com/49492887/101918527-2089ba00-3bd2-11eb-86e8-2e33d089ef5b.png)
![image](https://user-images.githubusercontent.com/49492887/101918549-267f9b00-3bd2-11eb-8b6b-1745446ebd4f.png)

**Comment by unDeadHerbs** [comment]
Is this a problem?  Isn't the card that wasn't swiped still in the stack?

**Comment by unDeadHerbs** [comment]
Closing due to probable lack of problem.
