### ISSUE TITLE
Unable to find in market place

### ISSUE THREAD

**Issue by shakeabi** [benawad/vsinder#56]
It was available in 1.49 edition ig, but couldn't install it as it asked me to update.
However, after I updated vscode to 1.51.1-1, vsinder no longer available in marketplace.

**Comment by gianpaj** [comment]
it's there
https://marketplace.visualstudio.com/items?itemName=benawad.vsinder.

Search for `vsinder`

<img width="320" src="https://user-images.githubusercontent.com/899175/101943144-82522000-3be2-11eb-9e96-9204199186eb.png" />

**Comment by shakeabi** [comment]
Yeah, tried that already, say "no extensions found".

![2020-12-12-142421_1920x1080_scrot](https://user-images.githubusercontent.com/36559835/101979857-b2eb9580-3c86-11eb-831c-6c3e28e08ea6.png)

Versions are mentioned in the image.
OS: Manjaro 20.2
Code installed using "pamac"

Note: It was showing in marketplace in code 1.49~

**Comment by gianpaj** [comment]
FYI: I'm on VScode 1.51.1
macOS Catalina 10.15.7

<img width="320" src="https://user-images.githubusercontent.com/899175/101993153-4a191300-3cb0-11eb-8206-cebc01c3b21d.png" />

**Comment by MananDesai54** [comment]
Try updating vscode to latest version

**Comment by shakeabi** [comment]
I updated, still same error, but seems like an issue from my end, I'm closing the issue.
