### ISSUE TITLE
login with github doesn't work

### ISSUE THREAD

**Issue by g-thome** [benawad/vsinder#66]
on android 9 after authorizing the app on github, it redirects me to the login screen

trying to press the login button again opens up a browser and that quickly closes itself.

**Comment by g-thome** [comment]
I have a Xiaomi Mi A1
this is what I get clicking on the link
![20201211_174651887.jpeg](https://user-images.githubusercontent.com/38537062/101953649-79a91c00-3bd9-11eb-98ca-592943562535.jpeg)

**Comment by g-thome** [comment]
this only happens on the android app. i could log in to the vscode extension just fine

**Comment by MananDesai54** [comment]
It is not happening at all, i tried on android IOS both

**Comment by benawad** [comment]
@g-thome what happens when you click the vsinder://tokens/a/b link?

**Comment by RedContritio** [comment]
> 
> 
> @g-thome what happens when you click the vsinder://tokens/a/b link?

<a style="font-size: 26px" href="vsinder://tokens/a/b">vsinder://tokens/a/b</a>

if I try open it, the browser will tell me can't solve protocol "vsinder".

**Comment by g-thome** [comment]
It just redirects me to the login screen. The new login button solved the problem for me tho. thanks :)
