### ISSUE TITLE
Internal Server Error after logging in

### ISSUE THREAD

**Issue by jeremeheh** [benawad/vsinder#69]
After logging in with github, I kept getting the error Internal Server Error

**Comment by benawad** [comment]
is this still happening to you?

**Comment by jeremeheh** [comment]
Tried logging in again, I'm still getting Internal Server Error

**Comment by benawad** [comment]
extension, android, or ios?

**Comment by RedContritio** [comment]
I guess this issue is as same as this [Login with Github Fails, even when VSCode Launched as Admin](https://github.com/shanalikhan/code-settings-sync/issues/1005)

And after I have searched for solutions, I found nothing helpful.

**Comment by unDeadHerbs** [comment]
Closed due to lack of second.

**Comment by Zac8668** [comment]
same error
