### ISSUE TITLE
Likes and Inbox count does not match . What is like count ?

### ISSUE THREAD

**Issue by DebashishSaha** [benawad/vsinder#71]
![image](https://user-images.githubusercontent.com/12764439/101950858-ff4dbb80-3c1b-11eb-9f14-ab9e9c9b8102.png)
It shows 25 but in inbox , only 1 . are you manipulating count :D :D

**Comment by schezfaz** [comment]
@DebashishSaha the likes indicate the total number of likes (right swipes) you have received! Now, you may have not swiped right on all of these in return. 

The inbox area only show the number of matches i.e. where both parties have swiped right!

**Comment by DebashishSaha** [comment]
> @DebashishSaha the likes indicate the total number of likes (right swipes) you have received! Now, you may have not swiped right on all of these in return.
> 
> The inbox area only show the number of matches i.e. where both parties have swiped right!

Never used tinder lol :D :D
