### ISSUE TITLE
[Feature request] Add possibility to see liked matches profiles after giving like

### ISSUE THREAD

**Issue by JJJGGGG** [benawad/vsinder#75]
Hi. I love the app. But maybe it would be interesting to have this feature, like in profile->liked profiles. I'll try to make a pr but I'm not so good with react-native lol.

**Comment by siramk** [comment]
It would also be nice to see the profiles who liked us

**Comment by unDeadHerbs** [comment]
Depending on how #20 progresses, this could become a privacy concern. (It also could even without it.)  Closing as duplicate of #78.
