### ISSUE TITLE
Ambiguous meaning on number of likes

### ISSUE THREAD

**Issue by isaacbernat** [benawad/vsinder#83]
Does this mean likes given, or likes received? Copy could include that info. Screenshot taken from Android app below:
![WhatsApp Image 2020-12-12 at 11 49 16](https://user-images.githubusercontent.com/2509809/101981884-57161200-3c70-11eb-946b-0fae003df527.jpeg)

Also it could be interesting to have both and calculate the ratio.

**Comment by lordvidex** [comment]
That is the number of likes gotten from other users.
